global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'mohamedanter845@gmail.com'
  smtp_auth_username: 'mohamedanter845@gmail.com'
  smtp_auth_password: 'abcd efgh ijkl mnop'
  smtp_require_tls: true

route:
  receiver: 'email-alert'

receivers:
- name: 'email-alert'
  email_configs:
  - to: 'mohamedanter845@gmail.com'
    send_resolved: true
