name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      ECR_REGISTRY: 792302461774.dkr.ecr.eu-north-1.amazonaws.com
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # -------------------------
      # Build & Push All Services
      # -------------------------

      - name: Build and Push ecommerce-frontend
        run: |
          docker build -t $ECR_REGISTRY/ecommerce-frontend:$IMAGE_TAG ./ecommerce-frontend
          docker push $ECR_REGISTRY/ecommerce-frontend:$IMAGE_TAG

      - name: Build and Push auth-service
        run: |
          docker build -t $ECR_REGISTRY/auth-service:$IMAGE_TAG ./auth-service
          docker push $ECR_REGISTRY/auth-service:$IMAGE_TAG

      - name: Build and Push product-service
        run: |
          docker build -t $ECR_REGISTRY/product-service:$IMAGE_TAG ./product-service
          docker push $ECR_REGISTRY/product-service:$IMAGE_TAG

      - name: Build and Push cart-service
        run: |
          docker build -t $ECR_REGISTRY/cart-service:$IMAGE_TAG ./cart-service
          docker push $ECR_REGISTRY/cart-service:$IMAGE_TAG

      - name: Build and Push order-service
        run: |
          docker build -t $ECR_REGISTRY/order-service:$IMAGE_TAG ./order-service
          docker push $ECR_REGISTRY/order-service:$IMAGE_TAG

      - name: Build and Push payment-service
        run: |
          docker build -t $ECR_REGISTRY/payment-service:$IMAGE_TAG ./payment-service
          docker push $ECR_REGISTRY/payment-service:$IMAGE_TAG

      - name: Build and Push notification-service
        run: |
          docker build -t $ECR_REGISTRY/notification-service:$IMAGE_TAG ./notification-service
          docker push $ECR_REGISTRY/notification-service:$IMAGE_TAG

      # -------------------------
      # Update kubeconfig (IMPORTANT)
      # -------------------------
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --name my-eks-cluster \
            --region eu-north-1

      # -------------------------
      # Restart Deployment
      # -------------------------
      - name: Restart frontend deployment
        run: |
          kubectl rollout restart deployment ecommerce-frontend -n default
